sudo: false

language: cpp

compiler:
  - gcc
  - clang

env:
  - PAM=0
  - PAM=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libpam0g-dev
      - libX11-dev
      - libx11-xcb-dev

cache:
  directories:
    - .cmake/3.3
    - .qt/5.6
    - .xcb/1.11

before_script:
  # Setup compilers
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  # Fetch and install dependencies if cache miss
  - bash -x .ci/fetch-cmake || exit 127
  - bash -x .ci/fetch-qt || exit 127
  - bash -x .ci/fetch-xcb || exit 127
  - export PATH=`pwd`/.cmake/3.3/bin:`pwd`/.qt/5.6/5.6/gcc_64/bin:`pwd`/.xcb/1.11/bin:$PATH
  - export LD_LIBRARY_PATH=`pwd`/.qt/5.6/5.6/gcc_64/lib:`pwd`/.xcb/1.11/lib:$LD_LIBRARY_PATH
  - export CMAKE_PREFIX_PATH=`pwd`/.qt/5.6/5.6/gcc_64/lib/cmake
  - export PKG_CONFIG_PATH=`pwd`/.xcb/1.11/lib/pkgconfig:$PKG_CONFIG_PATH
  # Prepare
  - mkdir build
  - cd build
  - if [ "$PAM" == "0" ]; then cmake -DENABLE_PAM:BOOL=OFF ..; fi
  - if [ "$PAM" == "1" ]; then cmake -DENABLE_PAM:BOOL=ON ..; fi

script:
  - make
