language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt4-dev-tools libpam0g-dev libX11-dev
  - sudo add-apt-repository ppa:czchen/travis-ci -y
  - sudo apt-get update -y
  - sudo apt-get install cmake -y 

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

